config/routes.rb
SistFirmas::Application.routes.draw do

  devise_for :users

devise_scope :user do match "/" => "pages#home" end

  root :to => "devise/sessions#new"

  resources :users, :path => '/admin/users'

  resources :request_types

  resources :principals

  resources :lists

  resources :rols

  resources :funds

  resources :requests
 
   match '/requests/:id/acept/',:controller =>'requests',:action => 'acept'
  match '/requests/:id/rejected/',:controller =>'requests',:action => 'rejected',:via=>'get',:as=>'rejected_request'

   
  match '/home/',:controller =>'pages',:action => 'home'

end

app/models/principal.rb
class Principal < ActiveRecord::Base
  attr_accessible :fund_id, :lista, :request_type_id
  belongs_to :fund
  belongs_to :request_type
end

app/controllers/principals_controller.rb
class PrincipalsController < ApplicationController
  # GET /principals
  # GET /principals.json
  before_filter :authenticate_user!
  load_and_authorize_resource
  def index
    @principals = Principal.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @principals }
    end
  end

  # GET /principals/1
  # GET /principals/1.json
  def show
    @principal = Principal.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @principal }
    end
  end

  # GET /principals/new
  # GET /principals/new.json
  def new
    @principal = Principal.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @principal }
    end
  end

  # GET /principals/1/edit
  def edit
    @principal = Principal.find(params[:id])
  end

  # POST /principals
  # POST /principals.json
  def create
    @principal = Principal.new(params[:principal])

    respond_to do |format|
      if @principal.save
        format.html { redirect_to @principal, notice: 'Principal was successfully created.' }
        format.json { render json: @principal, status: :created, location: @principal }
      else
        format.html { render action: "new" }
        format.json { render json: @principal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /principals/1
  # PUT /principals/1.json
  def update
    @principal = Principal.find(params[:id])

    respond_to do |format|
      if @principal.update_attributes(params[:principal])
        format.html { redirect_to @principal, notice: 'Principal was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @principal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /principals/1
  # DELETE /principals/1.json
  def destroy
    @principal = Principal.find(params[:id])
    @principal.destroy

    respond_to do |format|
      format.html { redirect_to principals_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/principals_helper.rb
module PrincipalsHelper
end

app/views/principals/_form.html.erb
<%= form_for(@principal) do |f| %>
  <% if @principal.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@principal.errors.count, "error") %> prohibited this principal from being saved:</h2>

      <ul>
      <% @principal.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :request_type_id %><br />
    <%= f.number_field :request_type_id %>
  </div>
  <div class="field">
    <%= f.label :fund_id %><br />
    <%= f.number_field :fund_id %>
  </div>
  <div class="field">
    <%= f.label :lista %><br />
    <%= f.number_field :lista %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/principals/edit.html.erb
<h1>Editing principal</h1>

<%= render 'form' %>

<%= link_to 'Show', @principal %> |
<%= link_to 'Back', principals_path %>

app/views/principals/index.html.erb
<h1>Listing principals</h1>

<table>
  <tr>
    <th>Request type</th>
    <th>Fund</th>
    <th>Lista</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @principals.each do |principal| %>
  <tr>
    <td><%= principal.request_type_id %></td>
    <td><%= principal.fund_id %></td>
    <td><%= principal.lista %></td>
    <td><%= link_to 'Show', principal %></td>
    <td><%= link_to 'Edit', edit_principal_path(principal) %></td>
    <td><%= link_to 'Destroy', principal, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Principal', new_principal_path %>

app/views/principals/new.html.erb
<h1>New principal</h1>

<%= render 'form' %>

<%= link_to 'Back', principals_path %>

app/views/principals/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Request type:</b>
  <%= @principal.request_type_id %>
</p>

<p>
  <b>Fund:</b>
  <%= @principal.fund_id %>
</p>

<p>
  <b>Lista:</b>
  <%= @principal.lista %>
</p>


<%= link_to 'Edit', edit_principal_path(@principal) %> |
<%= link_to 'Back', principals_path %>