config/routes.rb
SistFirmas::Application.routes.draw do

  devise_for :users

devise_scope :user do match "/" => "pages#home" end

  root :to => "devise/sessions#new"

  resources :users, :path => '/admin/users'

  resources :request_types

  resources :principals

  resources :lists

  resources :rols

  resources :funds

  resources :requests
 
   match '/requests/:id/acept/',:controller =>'requests',:action => 'acept'
  match '/requests/:id/rejected/',:controller =>'requests',:action => 'rejected',:via=>'get',:as=>'rejected_request'

   
  match '/home/',:controller =>'pages',:action => 'home'

end

app/models/request.rb
class Request < ActiveRecord::Base
  attr_accessible :descripcion, :fund_id, :request_type_id, :titulo
  belongs_to :request_type
  belongs_to :fund
  
end

app/models/request_type.rb
class RequestType < ActiveRecord::Base
  attr_accessible :nombre
  has_many :requests
  has_many :principals
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  # GET /requests
  # GET /requests.json

  before_filter :authenticate_user!
  load_and_authorize_resource

  def index
    @requests = Request.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @requests }
    end
  end

  # GET /requests/1
  # GET /requests/1.json
  def show
    @request = Request.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @request }
    end
  end

  # GET /requests/new
  # GET /requests/new.json
  def new
    @request = Request.new
    @request.active=TRUE
    @request.save
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @request }
    end
  end

  # GET /requests/1/edit
  def edit
    @request = Request.find(params[:id])
    unauthorized! if cannot? :edit, @request
  end

  # POST /requests
  # POST /requests.json
  def create
    @request = Request.new(params[:request])

    respond_to do |format|
      if @request.save
        format.html { redirect_to @request, notice: 'Request was successfully created.' }
        format.json { render json: @request, status: :created, location: @request }
      else
        format.html { render action: "new" }
        format.json { render json: @request.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /requests/1
  # PUT /requests/1.json
  def update
    @request = Request.find(params[:id])

    respond_to do |format|
      if @request.update_attributes(params[:request])
        format.html { redirect_to @request, notice: 'Request was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @request.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /requests/1
  # DELETE /requests/1.json
  def destroy
    @request = Request.find(params[:id])
    @request.destroy

    respond_to do |format|
      format.html { redirect_to requests_url }
      format.json { head :no_content }
    end
  end
  def acept
    @user= current_user
    @rol=Rol.find(@user)
    @request= Request.find(params[:id])
    unauthorized! if cannot? :acept, @request
    @request.estado= @rol.id
    @request.save
    respond_to do |format|
      format.html { redirect_to requests_url }
      format.json { head :no_content }
    end
  end
    def rejected
    @request= Request.find(params[:id])
    @user= current_user
    @rol=Rol.find(@user)
    unauthorized! if cannot? :acept, @request
    @request.estado= @rol.id
    @request.active=FALSE

    respond_to do |format|
      if @request.update_attributes(params[:request])
        format.html { redirect_to @request, notice: 'Request was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @request.errors, status: :unprocessable_entity }
      end
    end
  end
  
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/views/requests/_form.html.erb
<%= form_for(@request) do |f| %>

  <% if @request.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@request.errors.count, "error") %> prohibited this request from being saved:</h2>

      <ul>
      <% @request.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :titulo %><br />
    <%= f.text_field :titulo %>
  </div>
  <div class="field">
    <%= f.label :descripcion %><br />
    <%= f.text_area :descripcion %>
  </div>
  <div class="field">
    <%= f.label :request_type_id %><br />
    <%= f.number_field :request_type_id %>
  </div>
  <div class="field">
    <%= f.label :fund_id %><br />
    <%= f.number_field :fund_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>

 <%end%>

app/views/requests/edit.html.erb
<h1>Editing request</h1>

<%= render 'form' %>

<%= link_to 'Show', @request %> |
<%= link_to 'Back', requests_path %>

app/views/requests/index.html.erb
<h1>Listing requests</h1>
<h4>
<% @user= current_user %>
<%= current_user.email%>
<% @temp=@user.rol_ids%>
<%@rol=Rol.find(@temp[0])%>
<%=@rol.nombre%>
<%= link_to 'Salir', destroy_user_session_path %>
</h4>
<table>
  <tr>
    <th>Tituloo</th>
    <th>Descripción</th>
    <th>Tipo de requisición</th>
    <th>Fondo</th>
    <th>Estado</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @requests.each do |request| %>
  <tr>
  	<%if request.estado%>
    <%@estado=Rol.find(request.estado)%>
    
    <%else%>
    <%@estado.nombre=nil%>
    <%end%>
    <td><%= request.titulo %></td>
    <td><%= request.descripcion %></td>
    <%@tipo=RequestType.find(request.request_type_id )%>
    <td><%= @tipo.nombre %></td>
    <%@fondo=Fund.find(request.fund_id)%>
    <td><%= @fondo.nombre %></td>
    <td><%= @estado.nombre %></td>
    <td><%= link_to 'Ver', request %></td>
    <td>
    <% if can? :edit, @requests %>
    <% if @estado.nombre==nil%>
    <%= link_to 'Editar', edit_request_path(request) %>
    <%else%> Bloqueado 
    <%end%>
    <%end%>
    </td>
    <td>
    <%if can? :destroy, @requests%>
    <%= link_to 'Eliminar', request, method: :delete, data: { confirm: '¿Esta seguro?' } %></td>
    <%end%>
    <%if request.active==FALSE%>
    <td>!!</td>
    <%end%>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Nueva requisición', new_request_path %>

app/views/requests/new.html.erb
<h1>New request</h1>

<%= render 'form' %>

<%= link_to 'Back', requests_path %>

app/views/requests/rejected.html.erb
<h1>¿Por qué razones rechaza la solicitud?</h1>
<%= render 'form' %>

<%= link_to 'Show', @request %> |
<%= link_to 'Back', requests_path %>

app/views/requests/show.html.erb
<h4>
<% @user= current_user %>
<%= current_user.email%>
<% @temp=@user.rol_ids%>
<%@rol=Rol.find(@temp[0])%>
<%=@rol.nombre%>
<%= link_to 'Salir', destroy_user_session_path %>
</h4>
<p id="notice"><%= notice %></p>

<p>
  <b>Titulo:</b>
  <%= @request.titulo %>
</p>

<p>
  <b>Descripcion:</b>
  <%= @request.descripcion %>
</p>

<p>
  <b>Request type:</b>
  <%= @request.request_type_id %>
</p>

<p>
  <b>Fund:</b>
  <%= @request.fund_id %>
</p>
<%if @request.active==FALSE%>
<p>
	<h4>Requisición rechazada</h4>
</p>
<%end%>



<% if can? :edit, @request %>
<%= link_to 'Editar', edit_request_path(@request) %> |<%end%>
<% if can? :acept, @request %>
<%= link_to 'Aceptar', :controller => :requests, :action=>:acept %> |
<%end%>
<% if can? :rejected, @request %>
<%= link_to 'Rechazar', rejected_request_path(@request) %> |
<%end%>
<%= link_to 'Atras', requests_path %>