config/routes.rb
SistFirmas::Application.routes.draw do

  devise_for :users

devise_scope :user do match "/" => "pages#home" end

  root :to => "devise/sessions#new"

  resources :users, :path => '/admin/users'

  resources :request_types

  resources :principals

  resources :lists

  resources :rols

  resources :funds

  resources :requests
 
   match '/requests/:id/acept/',:controller =>'requests',:action => 'acept'
  match '/requests/:id/rejected/',:controller =>'requests',:action => 'rejected',:via=>'get',:as=>'rejected_request'

   
  match '/home/',:controller =>'pages',:action => 'home'

end

app/models/fund.rb
class Fund < ActiveRecord::Base
  attr_accessible :nombre
  has_many :requests
  has_many :principals
end

app/controllers/funds_controller.rb
class FundsController < ApplicationController
  # GET /funds
  # GET /funds.json
  before_filter :authenticate_user!
  load_and_authorize_resource
  def index
    @funds = Fund.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @funds }
    end
  end

  # GET /funds/1
  # GET /funds/1.json
  def show
    @fund = Fund.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @fund }
    end
  end

  # GET /funds/new
  # GET /funds/new.json
  def new
    @fund = Fund.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @fund }
    end
  end

  # GET /funds/1/edit
  def edit
    @fund = Fund.find(params[:id])
  end

  # POST /funds
  # POST /funds.json
  def create
    @fund = Fund.new(params[:fund])

    respond_to do |format|
      if @fund.save
        format.html { redirect_to @fund, notice: 'Fund was successfully created.' }
        format.json { render json: @fund, status: :created, location: @fund }
      else
        format.html { render action: "new" }
        format.json { render json: @fund.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /funds/1
  # PUT /funds/1.json
  def update
    @fund = Fund.find(params[:id])

    respond_to do |format|
      if @fund.update_attributes(params[:fund])
        format.html { redirect_to @fund, notice: 'Fund was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @fund.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /funds/1
  # DELETE /funds/1.json
  def destroy
    @fund = Fund.find(params[:id])
    @fund.destroy

    respond_to do |format|
      format.html { redirect_to funds_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/funds_helper.rb
module FundsHelper
end

app/views/funds/_form.html.erb
<%= form_for(@fund) do |f| %>
  <% if @fund.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@fund.errors.count, "error") %> prohibited this fund from being saved:</h2>

      <ul>
      <% @fund.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre %><br />
    <%= f.text_field :nombre %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/funds/edit.html.erb
<h1>Editing fund</h1>

<%= render 'form' %>

<%= link_to 'Show', @fund %> |
<%= link_to 'Back', funds_path %>

app/views/funds/index.html.erb
<h1>Listing funds</h1>

<table class="table table-striped">
  <tr>
    <th>Nombre</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @funds.each do |fund| %>
  <tr>
    <td><%= fund.nombre %></td>
    <td><%= link_to 'Show', fund %></td>
    <td><%= link_to 'Edit', edit_fund_path(fund) %></td>
    <td><%= link_to 'Destroy', fund, class: "btn btn-danger btn-mini",method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Fund', new_fund_path %>

app/views/funds/new.html.erb
<h1>New fund</h1>

<%= render 'form' %>

<%= link_to 'Back', funds_path %>

app/views/funds/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Nombre:</b>
  <%= @fund.nombre %>
</p>


<%= link_to 'Edit', edit_fund_path(@fund) %> |
<%= link_to 'Back', funds_path %>